# Post-Pandemic Gender Labor Force Trends
Principle Investigators: Abigail Garvey, Anna Wang, Rachelle Lang - Group Q

In [1]:
# uncomment if not installed - needed to save the table as an svg
!pip install dataframe-image matplotlib

Requirement already satisfied: dataframe-image in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (0.2.7)
Requirement already satisfied: matplotlib in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (3.8.4)
Requirement already satisfied: pandas>=0.24 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (2.2.2)
Requirement already satisfied: nbconvert>=5 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (6.5.4)
Requirement already satisfied: aiohttp>=3.10.2 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (3.13.2)
Requirement already satisfied: requests in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (2.32.3)
Requirement already satisfied: pillow in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (11.1.0)
Requirement already satisfied: packaging in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (25.0)
Requirement already satisfied: mistune in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (0.8.4)
Requirement already satisfied: lxml in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (5.3.0)
Requirement already satisfied: beautifulsoup4 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (4.13.4)
Requirement already satisfied: cssutils in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (2.11.1)
Requirement already satisfied: playwright in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (1.57.0)
Requirement already satisfied: cssselect in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from dataframe-image) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.21 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from aiohttp>=3.10.2->dataframe-image) (1.22.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from multidict<7.0,>=4.5->aiohttp>=3.10.2->dataframe-image) (4.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp>=3.10.2->dataframe-image) (3.7)
Requirement already satisfied: bleach in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (0.4)
Requirement already satisfied: jinja2>=3.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (3.1.6)
Requirement already satisfied: jupyter-core>=4.7 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (5.8.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (0.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (0.10.2)
Requirement already satisfied: nbformat>=5.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (5.3.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (1.5.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (2.19.1)
Requirement already satisfied: tinycss2 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (1.4.0)
Requirement already satisfied: traitlets>=5.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbconvert>=5->dataframe-image) (5.14.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe-image) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe-image) (311)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbclient>=0.5.0->nbconvert>=5->dataframe-image) (8.6.3)
Requirement already satisfied: pyzmq>=23.0 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe-image) (26.2.0)
Requirement already satisfied: tornado>=6.2 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5->dataframe-image) (6.5.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbformat>=5.1->nbconvert>=5->dataframe-image) (4.25.0)
Requirement already satisfied: fastjsonschema in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from nbformat>=5.1->nbconvert>=5->dataframe-image) (2.20.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert>=5->dataframe-image) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert>=5->dataframe-image) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert>=5->dataframe-image) (0.22.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from pandas>=0.24->dataframe-image) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from pandas>=0.24->dataframe-image) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from beautifulsoup4->dataframe-image) (2.5)
Requirement already satisfied: webencodings in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from bleach->nbconvert>=5->dataframe-image) (0.5.1)
Requirement already satisfied: more-itertools in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from cssutils->dataframe-image) (10.8.0)
Requirement already satisfied: pyee<14,>=13 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from playwright->dataframe-image) (13.0.0)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from playwright->dataframe-image) (3.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from requests->dataframe-image) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from requests->dataframe-image) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\famil\anaconda3\envs\econ570\lib\site-packages (from requests->dataframe-image) (2025.8.3)

In [2]:
import pandas as pd
import statsmodels.formula.api as smf
import datetime as dt
import dataframe_image as dfi

In [3]:
#read in industries data and change the date column to type datetime
industries = pd.read_csv("../Data/industries.csv")
industries["date"] =  pd.to_datetime(industries["date"])

In [4]:
#find all the unique industry codes
industry_codes = industries["indy_code"].unique()
# names of the industries in the dataset
industry_names = ["All Industries", "Agriculture and related industries", "Agriculture, forestry, fishing, and hunting", "Nonagriculture industries",
              "Mining, quarrying, and oil and gas extraction", "Utilities", "Construction", "Nondurable goods manufacturing",
              "Manufacturing", "Durable goods manufacturing", "Wholesale and retail trade", "Wholesale trade", "Retail trade",
              "Transportation and utilities", "Transportation and warehousing", "Information", "Financial activities",
             "Finance and insurance", "Real estate and rental and leasing", "Professional and business services", "Professional and technical services",
             "Management, administrative, and waste services", "Education and health services", "Educational services",
             "Health care and social assistance","Health service, except hospitals","Hospitals","Social assistance",
             "Leisure and hospitality","Arts, entertainment, and recreation", "Accommodation and food services", "Other services",
             "Other services, except private households", "Other services, private households", "Public administration"]

# map the codes to the names with a dictionary of the names
indy_code_to_name = dict(zip(industry_codes, industry_names))
industries['industry_name'] = industries['indy_code'].map(indy_code_to_name)

In [5]:
'''
used https://medium.com/@JuanPabloHerrera/why-interrupted-time-series-might-be-your-new-favorite-data-tool-399d260a9cd9
as an example of how to do interrupted time series analysis with regression
'''
# creating a mask for if the date is before or after covid
covid_start = pd.to_datetime("2020-03-01")
mask = industries['date'] > covid_start

# time column to show the number of months since the first month in the data, 1983-01-01
industries["time"] = (
    industries
    .groupby('indy_code')
    .cumcount()
)

# time_since_covid column to show the number of months since covid
industries["time_since_covid"] =  (
    industries[mask]
    .groupby('indy_code')
    .cumcount()
)

industries["post_covid"] = (industries["date"] >= covid_start).astype(int)
industries['time_since_covid'] = industries['time_since_covid'].fillna(0)

In [6]:
industries.head()

,indy_code,occupation_code,date,employed_men,employed_women,employed_total,pct_men,pct_women,industry_name,time,time_since_covid,post_covid
0,0,7,1983-01-01,16410.0,12123.0,28533.0,0.575124,0.424876,All Industries,0,0.0,0
1,0,7,1983-02-01,16355.0,12225.0,28580.0,0.572253,0.427747,All Industries,1,0.0,0
2,0,7,1983-03-01,16491.0,12201.0,28692.0,0.574760,0.425240,All Industries,2,0.0,0
3,0,7,1983-04-01,16759.0,12366.0,29125.0,0.575416,0.424584,All Industries,3,0.0,0
4,0,7,1983-05-01,16825.0,12367.0,29192.0,0.576357,0.423643,All Industries,4,0.0,0

In [7]:
# filtering the industries to just include 5 years pre and post covid
filteredIndustries = industries[(industries["date"] >= dt.datetime(2015, 3, 1)) & (industries["date"] <= dt.datetime(2025, 3, 1))]

In [8]:
results = {}

# run an ols regression on each of the industries in the filteredIndustries dataset and uses robust standard errors
for industry, group in filteredIndustries.groupby('industry_name'):
    model = smf.ols("employed_total ~ time + post_covid + C(occupation_code) + time_since_covid", data=group).fit(cov_type="HC3")
    df_result = pd.DataFrame({
        "coef": model.params,
        "pvalue": model.pvalues
    })
    results[industry] = df_result

In [9]:
# turn all the regression results into a dataframe
results = pd.concat(results, names=["industry_name", "variable"])
results = results.reset_index()
results

,industry_name,variable,coef,pvalue
0,Accommodation and food services,Intercept,8146.596374,6.202449e-14
1,Accommodation and food services,time,6.724999,1.044773e-02
2,Accommodation and food services,post_covid,-2219.594202,7.618754e-14
3,Accommodation and food services,time_since_covid,31.625314,6.559766e-05
4,Agriculture and related industries,Intercept,2597.695455,0.000000e+00
...,...,...,...,...
368,Wholesale trade,C(occupation_code)[T.7699],-2114.520391,2.290422e-17
369,Wholesale trade,C(occupation_code)[T.8999],-1439.937719,1.438873e-07
370,Wholesale trade,time,-0.623928,4.504722e-07
371,Wholesale trade,post_covid,-78.686599,2.474464e-12
372,Wholesale trade,time_since_covid,0.157063,7.229429e-13

In [10]:
# These industries had a significant negative time_since_covid pvalue
filteredNegInd = results[(results["pvalue"] < 0.05) & (results["coef"] < 0) & (results["variable"] == "time_since_covid")]
filteredNegInd = filteredNegInd.drop(["variable"], axis=1)
filteredNegInd = filteredNegInd.rename(columns={'industry_name': 'Industry', 'pvalue': 'p-value'})
filteredNegInd.reset_index(drop=True, inplace = True)

In [11]:
filteredNegInd

                               Industry       coef       p-value
0                        All Industries  -1.699006  4.571251e-94
1                          Construction  -0.570648  8.109740e-21
2           Durable goods manufacturing  -0.180732  1.297836e-05
3         Education and health services  -1.032716  1.083943e-14
4                  Financial activities  -0.498793  1.164736e-44
5                             Hospitals  -7.183301  1.085244e-04
6                           Information  -0.059068  1.639361e-03
7                         Manufacturing  -0.233386  5.294496e-05
8        Nondurable goods manufacturing  -0.052836  3.495780e-02
9    Professional and business services  -1.523461  2.891103e-45
10  Professional and technical services -12.439522  6.355289e-06
11                Public administration  -0.559998  4.963299e-52
12   Real estate and rental and leasing  -3.087646  4.888980e-02
13         Transportation and utilities  -0.538424  5.957658e-12

In [12]:
# Saving the dataframe as an svg
filename = 'negative_trends_industries.svg'
dfi.export(filteredNegInd, filename, table_conversion='matplotlib')

print(f"Successfully saved DataFrame to {filename}")

Successfully saved DataFrame to negative_trends_industries.svg

In [13]:
# These industries had a significant positive time_since_covid pvalue
filteredPosInd = results[(results["pvalue"] < 0.05) & (results["coef"] > 0) & (results["variable"] == "time_since_covid")]
filteredPosInd = filteredPosInd.drop(["variable"], axis=1)
filteredPosInd = filteredPosInd.rename(columns={'industry_name': 'Industry', 'pvalue': 'p-value'})
filteredPosInd.reset_index(drop=True, inplace = True)

In [14]:
filteredPosInd

                                          Industry        coef       p-value
0                  Accommodation and food services   31.625314  6.559766e-05
1               Agriculture and related industries    0.092501  2.459063e-15
2              Arts, entertainment, and recreation   14.570427  3.315552e-07
3                             Educational services   10.920603  2.850981e-04
4                Health care and social assistance   19.880557  5.388884e-06
5                 Health service, except hospitals   15.254989  1.345643e-07
6                          Leisure and hospitality    0.723205  3.581095e-09
7   Management, administrative, and waste services   28.462852  3.923042e-17
8    Mining, quarrying, and oil and gas extraction    0.081893  4.699305e-14
9                        Nonagriculture industries  138.567645  9.781431e-05
10              Other services, private households    0.077058  3.240005e-18
11                                    Retail trade    0.851607  3.668877e-22
12                               Social assistance   11.803764  6.552757e-15
13                                       Utilities    1.425176  3.096439e-02
14                      Wholesale and retail trade    1.008381  3.325405e-25
15                                 Wholesale trade    0.157063  7.229429e-13

In [15]:
# saving the dataframe as an SVG
filename = 'positive_trends_industries.svg'
dfi.export(filteredPosInd, filename, table_conversion='matplotlib')

print(f"Successfully saved DataFrame to {filename}")

Successfully saved DataFrame to positive_trends_industries.svg